### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by PeterGarlic** [cernops/rundeck-exec-kerberos#3]
https://github.com/cernops/rundeck-exec-kerberos/raw/master/ssh-krb-node-executor-plugin.zip

**Comment by danifr** [comment]
Hi @PeterGarlic,

sorry for the late response on this. I completely missed it.
A few months ago, we decided to move the binaries to the releases tab.

You can now find them here: https://github.com/cernops/rundeck-exec-kerberos/releases

Also, I encourage you to use the latest version, available here: https://github.com/cernops/rundeck-exec-kerberos/releases/download/v1.3/rundeck-ssh-krb-node-executor-plugin-1.3.zip

Thanks,
Daniel.
