### ISSUE TITLE
possibility to forward krb token

### ISSUE THREAD

**Issue by beer4duke** [cernops/rundeck-exec-kerberos#4]
Thank you for this plugin.
Currently the krb token is not forwarded on the remote host.
This would be very useful to allow users to xrdcp a file from remote host to an eos instance for example.
For now we need to scp the keytab, kinit on the remote host.

**Comment by philippeganz** [comment]
Thanks for reporting. We will add the forwarding to the script soon.
As a workaround, you can add the `GSSAPIDelegateCredentials yes` to your /etc/ssh/ssh_config or ~/.ssh.config file. This will have the same effect.

**Comment by philippeganz** [comment]
Fix in #5

**Comment by philippeganz** [comment]
Deployed
